services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=trello
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=Naga@root
      - NODE_ENV=production
    depends_on:
      - database

  database:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Naga@root
      - POSTGRES_DB=trello
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
